name = "HomotopyContinuation"
uuid = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
license = "MIT"
author = ["Sascha Timme <timme@math.tu-berlin.de>", "Paul Breiding <breidings@mis.mpg.de>"]
version = "0.8.0-dev"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
FixedPolynomials = "3dd14ad9-0029-526e-86e9-8aa0bdd2ab0d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ProjectiveVectors = "01f381cc-face-5a0a-ade9-ef63dc65d628"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticPolynomials = "62e018b1-6e46-5407-a5a7-97d4fbcae734"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TreeViews = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"

[compat]
julia = "^1.1"
DynamicPolynomials = "^0.1.2"
FixedPolynomials = "^0.4.0"
MultivariatePolynomials = "^0.2.3"
Parameters = "^0.10.3"
ProgressMeter = "^0.8.0, ^0.9.0, ^1.0"
ProjectiveVectors = "^0.2.0"
StaticArrays = "^0.8, ^0.9, ^0.10"
StaticPolynomials = "^1.0.0"
TreeViews = "^0.3.0"

[extras]
PolynomialTestSystems = "4c526841-e1e8-562c-bfa9-9f39d642e243"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PolynomialTestSystems", "Test"]
